config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :organisations, only: [:show, :edit]
  resource :assignment, only: [:show, :edit]
  resolve('Assignment') { [:assignment] }

  get "org/:org_name/raw-data",   to: "organisations#raw_data"
  post "send-message/",           to: "organisations#send_message"
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def show
    get_resource_data
  end
  def edit
    get_resource_data
    @props = { name: "Stranger" }
  end

  def get_resource_data
    params.permit :organisation_id
    @organisation = Organisation.find(params[:organisation_id])
    @resource_groups = @organisation.resource_groups
    @unassigned_resources = @organisation.unassigned_resources
  end
end

app/views/assignments/edit.html.erb
Edit resource assignment
<%= react_component("ResourceAssignment", props: @props, prerender: false) %>

app/views/assignments/show.html.erb
<h1>Resource assignment</h1>

<p>
  <% @resource_groups.each do |g| %>
  <h3>Assigned resources:</h3>
  <p><%= g.name %> assigned: <%= g.resource_assignments.pluck(:no_slots).sum %> slots</p>
  <ul>
    <% g.resource_assignments.each do |a| %>
    <li><%= a.resource.platform %> <%= a.resource.resource_class %> - <%= a.no_slots %> slots</li>
      <% end %>
  </ul>
<% end %>

</p>

<p>
  <h3>Unassigned</h3>
<ul>
  <% @unassigned_resources.each do |res| %>
    <li><%= res[:resource].platform %> <%= res[:resource].resource_class %> - <%= res[:unassigned_slots] %> / <%= res[:resource].slot_capacity %> slots</li>
  <% end %>
</ul>
</p>
<%= link_to 'Edit', edit_assignment_path(organisation_id: @organisation.id) %>