config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :organisations, only: [:show, :edit]
  resource :assignment, only: [:show, :edit]
  resolve('Assignment') { [:assignment] }

  get "org/:org_name/raw-data",   to: "organisations#raw_data"
  post "send-message/",           to: "organisations#send_message"
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :resources, dependent: :destroy
  has_many :resource_groups, dependent: :destroy

  validates :name, presence:true, uniqueness: true

  def pretty_display
    msg = "'#{self.name}:'"
    self.attributes.each do |field, value|
      if !['id', 'created_at', 'updated_at'].include?(field)
        msg << "\n\t#{field.humanize(keep_id_suffix: true)}: #{value}"
      end
    end
    msg
  end

  def send_message(msg)
    Slack.send_message(self.channel_id, msg)
  end

  def unassigned_resources
    resources.map do |res|
      if res.unassigned_slots > 0
        {
          resource: res,
          unassigned_slots: res.unassigned_slots,
        }
      end
    end.compact
  end
end

app/controllers/organisation_controller.rb
class OrganisationController < ApplicationController

  def show
    @org = Organisation.find_by(name: params[:org_name])
  end

  def change
    @org = Organisation.find_by(name: params[:org_name])
  end

  def raw_data
    org = Organisation.find_by(name: params[:org_name])
    response = {
      'organization' => {
        'name' => org.name
      },
      'date' => {
        'startDate' => 12345678,
        'endDate' => 12345678
      },
    }
    resources = []
    org.resources.each do |res|
      resources << { 
        'id': res.id,
        'platform': res.platform,
        'location': res.location,
        'resource_class': res.resource_class,
        'capacity': { 
          'dedicated': res.burst ? 0 : res.slot_capacity,
          'utilizedBurst': res.burst ? (res.slot_capacity * 0.1).round : 0,
          'maxBurst': res.burst ? res.slot_capacity : 0,
          'utilizedTotal': res.burst ? 0 : (res.slot_capacity * 0.6).round,
          'maxTotal': res.slot_capacity
        },
        'cost': { 
          'dedicated': res.burst ? 0 : res.cost,
          'utilizedBurst': res.burst ? (res.cost * 0.1).round(2) : 0 ,
          'maxBurst': res.burst ? res.cost : 0,
          'utilizedTotal': res.burst ? 0 : (res.cost * 0.6).round(2),
          'maxTotal': res.cost
        }
      }
    end
    response[:resources] = resources

    capacity = {
      'dedicated' => resources.sum{ |h| h[:capacity][:dedicated] },
      'utilizedBurst' => resources.sum{ |h| h[:capacity][:utilizedBurst] },
      'maxBurst' => resources.sum{ |h| h[:capacity][:maxBurst] },
      'utilizedTotal' => resources.sum{ |h| h[:capacity][:utilizedTotal] },
      'maxTotal' => resources.sum{ |h| h[:capacity][:maxTotal] }
    }
    response[:capacity] = capacity

    cost = {
      'dedicated' => resources.sum{ |h| h[:cost][:dedicated] },
      'utilizedBurst' => resources.sum{ |h| h[:cost][:utilizedBurst] },
      'maxBurst' => resources.sum{ |h| h[:cost][:maxBurst] },
      'utilizedTotal' => resources.sum{ |h| h[:cost][:utilizedTotal] },
      'maxTotal' => resources.sum{ |h| h[:cost][:maxTotal] }
    }

    response[:cost] = cost

    render json: response
  end

  def send_message
    org = Organisation.find(params["org_id"])
    res = org.resources.find_by(id: params["resource_id"])
    change_request = ChangeRequest.new(resource_id: res.id)

    msg = ""
    params.each do |key, value|
      if !['resource_id', 'controller', 'action', 'org_id'].include?(key) && (res[key].to_s != value) && !value.blank?
        change_request[key] = value
        msg << "\n\t*#{key.humanize(keep_id_suffix: true)}:* #{res[key]} -> *#{value}*"
      end
    end
    if !msg.blank?
      msg = "-" * 30 + "\nChange request received from *#{org.name}* for *resource ##{res.id}*:" + msg
      org.send_message(msg)
      change_request.save
    end
  end

end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController

  def show
    @org = Organisation.find(params[:id])
  end

  def edit
    @org = Organisation.find(params[:id])
  end

  def raw_data
    org = Organisation.find_by(name: params[:org_name])
    response = {
      'organization' => {
        'name' => org.name
      },
      'date' => {
        'startDate' => 12345678,
        'endDate' => 12345678
      },
    }
    resources = []
    org.resources.each do |res|
      resources << { 
        'id': res.id,
        'platform': res.platform,
        'location': res.location,
        'resource_class': res.resource_class,
        'capacity': { 
          'dedicated': res.burst ? 0 : res.slot_capacity,
          'utilizedBurst': res.burst ? (res.slot_capacity * 0.1).round : 0,
          'maxBurst': res.burst ? res.slot_capacity : 0,
          'utilizedTotal': res.burst ? 0 : (res.slot_capacity * 0.6).round,
          'maxTotal': res.slot_capacity
        },
        'cost': { 
          'dedicated': res.burst ? 0 : res.cost,
          'utilizedBurst': res.burst ? (res.cost * 0.1).round(2) : 0 ,
          'maxBurst': res.burst ? res.cost : 0,
          'utilizedTotal': res.burst ? 0 : (res.cost * 0.6).round(2),
          'maxTotal': res.cost
        }
      }
    end
    response[:resources] = resources

    capacity = {
      'dedicated' => resources.sum{ |h| h[:capacity][:dedicated] },
      'utilizedBurst' => resources.sum{ |h| h[:capacity][:utilizedBurst] },
      'maxBurst' => resources.sum{ |h| h[:capacity][:maxBurst] },
      'utilizedTotal' => resources.sum{ |h| h[:capacity][:utilizedTotal] },
      'maxTotal' => resources.sum{ |h| h[:capacity][:maxTotal] }
    }
    response[:capacity] = capacity

    cost = {
      'dedicated' => resources.sum{ |h| h[:cost][:dedicated] },
      'utilizedBurst' => resources.sum{ |h| h[:cost][:utilizedBurst] },
      'maxBurst' => resources.sum{ |h| h[:cost][:maxBurst] },
      'utilizedTotal' => resources.sum{ |h| h[:cost][:utilizedTotal] },
      'maxTotal' => resources.sum{ |h| h[:cost][:maxTotal] }
    }

    response[:cost] = cost

    render json: response
  end

  def send_message
    org = Organisation.find(params["org_id"])
    res = org.resources.find_by(id: params["resource_id"])
    change_request = ChangeRequest.new(resource_id: res.id)

    msg = ""
    params.each do |key, value|
      if !['resource_id', 'controller', 'action', 'org_id'].include?(key) && (res[key].to_s != value) && !value.blank?
        change_request[key] = value
        msg << "\n\t*#{key.humanize(keep_id_suffix: true)}:* #{res[key]} -> *#{value}*"
      end
    end
    if !msg.blank?
      msg = "-" * 30 + "\nChange request received from *#{org.name}* for *resource ##{res.id}*:" + msg
      org.send_message(msg)
      change_request.save
    end
  end

end

app/views/organisations/edit.html.erb
<h1><%= "Page for #{@org.name}"%></h1>

<h2>Modify an existing resource:</h2>
<table>
  <form action="/send-message" method="post">
    <input type="hidden" name="org_id" value=<%= "#{@org.id}" %> />
    <tr>
      <td> Resource ID: </td>
      <td>
        <select name="resource_id">
          <% @org.resources.each do |res| %>
            <option value= <%= res.id %>> <%= "##{res.id}" %> </option>
          <% end %>
        </select>
      </td>
    </tr>
    <% Resource.columns_hash.values.each do |field| %>
      <tr>
        <% if !['id', 'organisation_id', 'created_at', 'updated_at', 'cost', 'burst'].include?(field.name) %>
          <% display_name = field.name.humanize(keep_id_suffix: true) %>
          <td> <%= "#{display_name}:" %> </td>
          <td><input type="text" name="<%= field.name %>"></td>
        <% end %>
      </tr>
    <% end %>
    <td> Usage: </td>
    <td>
      <select name="burst">
        <option value= false> Dedicated </option>
        <option value= true> Burst </option>
      </select> <br>
    </td>

    <tr><td colspan="2"><input type="submit" value="Submit request" style="height:35px; width:300px"></td></tr>
  </form>
</table>

app/views/organisations/show.html.erb
<!doctype html>
<html>

<head>
	<title>Concertim | Powered by Alces Flight</title>
	<meta charset="utf-8">
    <script>var organisation = "<%= @org.name %>"</script>
	<link rel="stylesheet" type="text/css" href="../c/index.css" />
	<script type="text/javascript" src="../j/jquery.3.5.1.min.js"></script>
	<script type="text/javascript" src="../j/echarts.min.js"></script>
</head>

<body>
		<div id="nav-bar"></div>
		<h1 id="main-title"></h1>
		<div id="overview-wrapper">
			<div id="monthly-overview">
				<h2 class="board-title">Monthly Overview</h2>
				<p id="audit-date">06.01.2024 - 10.06.2024</p>
				<div id="capacity-data-wrapper" class="monthly-overview-data-wrapper"></div>
				<div id="capacity-bar" class="monthly-overview-bar"></div>
				<div id="cost-data-wrapper" class="monthly-overview-data-wrapper"></div>
				<div id="cost-bar" class="monthly-overview-bar"></div>
			</div>
			<div id="platform-capacity-pie-chart" class="platform-breakdown-chart">Capacity</div>
			<div id="platform-cost-pie-chart" class="platform-breakdown-chart">Cost</div>
			<div id="platform-legend-wrapper">
				<p id="platform-legend-sort">Sort by: Name A-Z</p>
				<div id="platform-legend-list-wrapper">
					<div id="platform-legend-scroll-wrapper"></div>
				</div>
			</div>
			<div id="resource-dimension-box"></div>
			<div id="resource-wrapper">
				<div id="resource-return"></div>
				<h2 class="board-title">Global Resources</h2>
                <div class="board-content">
                  <% @org.resources.each do |resource| %>
                    <p><%= resource.slot_capacity %> slots of '<%= resource.resource_class %>' on <%= resource.platform %> in <%= resource.location %></p>
                  <%end%>
                </div>
				<%= link_to 'Resource assignments', assignment_path(organisation_id: @org.id) %>
			</div>
		</div>
    <div id="earth-wrapper">
			<div id="earth-scene-wrapper"></div>
				<div id="uk" class="earth-anchor" flight-location="GBR">3</div>
    </div>

	<script type="module" src="../j/earth/earth.js"></script>
	<script type="text/javascript" src="../j/index.js"></script>
</body>

</html>